import text from "./text";

export default {
  aboutSelectable: [
    { title: "What Is PocketScholar?", text: text.aboutText.whatIsPs },
    {
      title: "Why Does PocketScholar Exist?",
      text: text.aboutText.whyDoesPsExist,
    },
    {
      title: "Why Does PocketScholar Exist? Pt. 2",
      text: text.aboutText.whyDoesPsExist2,
    },
    { title: "What are Info Pages?", text: text.aboutText.psInfoPages },
    { title: "About Page", text: text.aboutText.aboutPage },
    { title: "Get Started Page", text: text.aboutText.getStartedPage },
    { title: "Challenges Page", text: text.aboutText.challengesPage },
    {
      title: "What are Interactable Pages?",
      text: text.aboutText.psInteractable,
    },
    { title: "Activity List", text: text.aboutText.activityList },
    { title: "Scholarship Tracker", text: text.aboutText.tracker },
    { title: "Prompts Page", text: text.aboutText.promptsPage },
    { title: "Resources Page", text: text.aboutText.resourcesPage },
    { title: "Developer Notes", text: text.aboutText.notes },
  ],
  getStartedSelectable: [
    {
      title: "What is a Scholarship?",
      text: text.getStartedText.whatsAScholarship,
    },
    {
      title: "Invest In Yourself First!",
      text: text.getStartedText.investInYourself,
    },
    {
      title: "The Investment Equations",
      text: text.getStartedText.investmentEquations,
    },
    {
      title: "Investment Equations 1 and 2",
      text: text.getStartedText.equations1and2,
    },
    {
      title: "Investment Equation 3",
      text: text.getStartedText.equation3,
    },
    {
      title: "Equation 3, The Ingredients",
      text: text.getStartedText.breakdownIngredients,
    },
    {
      title: "Equation 3, The Results",
      text: text.getStartedText.breakdownResults,
    },
    { title: "Applying Equation 3", text: text.getStartedText.applyEquation3 },
    { title: "Fashion Your Passion", text: text.getStartedText.fashionPassion },
    { title: "Hide and Seek", text: text.getStartedText.hideAndSeek },
    { title: "Break Out", text: text.getStartedText.breakOut },
    { title: "The Patient", text: text.getStartedText.youThePatient },
    { title: "Recap", text: text.getStartedText.recap },
  ],
  challengesSelectable: [
    { title: "Time Management", text: text.challengesText.timeMgmt },
    { title: "Burnout", text: text.challengesText.burnout },
    { title: "Impostor Syndrome", text: text.challengesText.impostor },
    { title: "Dabbling", text: text.challengesText.dabbling },
    {
      title: "Finding The Right Opportunities For You",
      text: text.challengesText.opportunities,
    },
  ],
  promptSelectable: [
    "Describe the impact of your greatest volunteer undertaking. What inspired you to do it?",
    "Illustrate your top three achievements.",
    "Talk about a time you left your comfort zone. What happened and what did you learn?",
    "What obstacles have you faced in leadership positions? How did you overcome them?",
    "Describe your favorite lesson learned from a leadership experience? How did you learn it?",
    "What is your greatest strength? Give an example of a time it benefitted you.",
    "What is your greatest weakness? What do you do to regulate it?",
    "Who has been an important role model for you?",
    "On what occasion have you taken the initiative to fulfill a need at your school or in your community?",
    "Tell the story of a mistake you’ve made. What were the consequences and what did you learn?",
    "Where do you see yourself in 10 years?",
  ],
  resourcesSelectable: [
    {
      title: "1. Scholarship Search Engines",
      text: text.resourcesText.searchEngines,
    },
    {
      title: "Scholarships Canada",
      text: text.resourcesText.scholarshipsCanada,
      url: "https://www.scholarshipscanada.com/Index.aspx",
      linkName: "ScholarshipsCanada.com",
    },
    {
      title: "ScholarTree",
      text: text.resourcesText.scholartree,
      url: "https://scholartree.ca/",
      linkName: "ScholarTree.ca",
    },
    {
      title: "Yconic",
      text: text.resourcesText.yconic,
      url: "http://yconic.com/",
      linkName: "Yconic.com",
    },
    {
      title: "StudentAwards",
      text: text.resourcesText.studentAwards,
      url: "https://studentawards.com/",
      linkName: "StudentAwards.com",
    },
    {
      title: "Student Aid and Education Planning",
      text: text.resourcesText.studentAid,
      url: "https://www.canada.ca/en/services/benefits/education.html",
      linkName: "Student Aid and Education Planning",
    },
    {
      title: "2. Book Recommendations",
      text: text.resourcesText.books,
      url: "https://www.ascd.org/el/articles/too-dumb-for-complex-texts",
      linkName: "Too Dumb for Complex Texts?",
    },
    {
      title: "Amusing Ourselves To Death",
      text: text.resourcesText.amusingToDeath,
      url: "https://www.goodreads.com/book/show/74034.Amusing_Ourselves_to_Death",
      linkName: "Amusing Ourselves To Death - Goodreads",
    },
    {
      title: "Atomic Habits",
      text: text.resourcesText.atomicHabits,
      url: "https://www.goodreads.com/book/show/40121378-atomic-habits?from_search=true&from_srp=true&qid=CEiRQUwI0o&rank=1",
      linkName: "Atomic Habits - Goodreads",
    },
    {
      title: "Getting to Yes",
      text: text.resourcesText.gettingToYes,
      url: "https://www.goodreads.com/book/show/313605.Getting_to_Yes?ac=1&from_search=true&qid=AkUBIbTTct&rank=1",
      linkName: "Getting to Yes - Goodreads",
    },
    {
      title: "How To Read a Book",
      text: text.resourcesText.readABook,
      url: "https://www.goodreads.com/book/show/567610.How_to_Read_a_Book?from_search=true&from_srp=true&qid=ybcqLxHR1a&rank=1",
      linkName: "How To Read a Book - Goodreads",
    },
    {
      title: "Influence, The Psychology of Persuasion",
      text: text.resourcesText.influence,
      url: "https://www.goodreads.com/book/show/28815.Influence?ac=1&from_search=true&qid=LpIIie73Ic&rank=2",
      linkName: "Influence - Goodreads",
    },
    {
      title: "Range, Why Generalists Triumph in a Specialized World",
      text: text.resourcesText.range,
      url: "https://www.goodreads.com/book/show/41795733-range?ac=1&from_search=true&qid=nyzSjTHscv&rank=1",
      linkName: "Range - Goodreads",
    },
    {
      title: "Rich Dad Poor Dad",
      text: text.resourcesText.richDadPoorDad,
      url: "https://www.goodreads.com/book/show/69571.Rich_Dad_Poor_Dad?ac=1&from_search=true&qid=pMapeCCD6Z&rank=1",
      linkName: "Rich Dad Poor Dad - Goodreads",
    },
    {
      title: "The 4 Hour Workweek",
      text: text.resourcesText.workweek,
      url: "https://www.goodreads.com/book/show/368593.The_4_Hour_Workweek?ac=1&from_search=true&qid=Lr9VEfaoOk&rank=1",
      linkName: "The 4-Hour Workweek - Goodreads",
    },
    {
      title: "The Barefoot Investor",
      text: text.resourcesText.barefootInvestor,
      url: "https://www.goodreads.com/book/show/33121747-the-barefoot-investor?ac=1&from_search=true&qid=3hmtVeUUEQ&rank=1",
      linkName: "The Barefoot Investor - Goodreads",
    },
    {
      title: "The Bitcoin Standard",
      text: text.resourcesText.bitcoinStandard,
      url: "https://www.goodreads.com/book/show/36448501-the-bitcoin-standard?ac=1&from_search=true&qid=cuhVky8uWy&rank=1",
      linkName: "The Bitcoin Standard - Goodreads",
    },
    {
      title: "The Ride of a Lifetime",
      text: text.resourcesText.rideOfALifetime,
      url: "https://www.goodreads.com/book/show/44525305-the-ride-of-a-lifetime?ac=1&from_search=true&qid=iXnecl4jtc&rank=1",
      linkName: "The Ride of a Lifetime - Goodreads",
    },
    {
      title: "The Velvet Rope Economy",
      text: text.resourcesText.velvetRope,
      url: "https://www.goodreads.com/book/show/50064632-the-velvet-rope-economy?ac=1&from_search=true&qid=oRCE5ILN87&rank=1",
      linkName: "The Velvet Rope Economy- Goodreads",
    },
    {
      title: "Thinking Fast and Slow",
      text: text.resourcesText.thinkingFastSlow,
      url: "https://www.goodreads.com/book/show/11468377-thinking-fast-and-slow?ac=1&from_search=true&qid=rIoDxawQfs&rank=1",
      linkName: "Thinking Fast and Slow - Goodreads",
    },
    {
      title: "3. Additional Resources",
      text: text.resourcesText.additionalResources,
    },
    {
      title: "Extracurricular Inspiration",
      text: text.resourcesText.inspiration,
      url: "https://blog.collegevine.com/your-complete-list-of-extracurricular-activities/",
      linkName: "100's of Extracurriculars",
    },
    {
      title: "Compound Interest",
      text: text.resourcesText.compoundInterest,
      url: "https://www.thebalance.com/compound-interest-4061154",
      linkName: "What is Compound Interest?",
    },
    {
      title: "Financial Toolkit",
      text: text.resourcesText.financialToolkit,
      url: "https://www.canada.ca/en/financial-consumer-agency/services/financial-toolkit.html",
      linkName: "The Canadian Government's Financial Toolkit",
    },
    {
      title: "LinkedIn",
      text: text.resourcesText.LinkedIn,
      url: "https://www.linkedin.com/pulse/7-benefits-using-linkedin-sarah-rycraft/",
      linkName: "Benefits of LinkedIn",
    },
    { title: "4. Sources", text: text.resourcesText.sources },
    {
      title: "Trends in Student Debt",
      text: text.resourcesText.trendsStudentDebt,
      url: "https://www150.statcan.gc.ca/n1/pub/75-006-x/2020001/article/00005-eng.htm",
      linkName: "Trends in Student Debt",
    },
    {
      title: "Student Debtor Analysis",
      text: text.resourcesText.studentDebtorAnalysis,
      url: "https://www.hoyes.com/press/joe-debtor/the-student-debtor/",
      linkName: "Student Debtor Analysis",
    },
  ],
};
