export default {
  aboutText: {
    whatIsPs:
      "PocketScholar is a volunteer project geared towards students to spark thoughts about how they’ll fund their post-secondary education and set themselves up for a successful future. Making yourself a successful candidate for scholarships is by far the most time effective way to finance yourself and develop crucial skills in the process. By getting a head start and making a sensible investment of time and effort, you can kickstart your financial future to lead a more generous, ambitious, and vibrant life!\n\n" +
      "PocketScholar isn’t a tool to help you find scholarships, nor is it a guide on how to successfully apply for them; there are already plenty of those to choose from! What it can be, however, is a catalyst for exceptional growth in many areas of your life. To successfully utilize PocketScholar, you are encouraged to do the thinking and the work that comes with it, because I don’t hope to help you win scholarships, I want you to become <i>the type of person</i> who wins scholarships!\n\n" +
      "While scholarship awards may be your inspiration for picking up PocketScholar, money or not, you have the capacity to be a better person by reflecting and acting upon what this app has to offer. By outlining the blueprint for success, shifting your perspective, and posing questions that will force you to think about what lies ahead, PocketScholar will help you lay the path to prosperity far beyond solely winning scholarships. Now the only question is, will you follow it?\n\n",
    whyDoesPsExist:
      "The drive behind PocketScholar’s development is multifaceted, though the primary motivation stems from two main sources.\n\n" +
      "I entered high school as a respectable, but not quite outstanding student. I had always been studious when it came to academics, and also took my athletics and arts very seriously. I felt successful, my parents never complained about my grades, nor my teachers about my behaviour, yet by personal preference I remained confined to the ecosystem that I had slowly formed throughout childhood, slowing my personal growth in the process. I wish I had PocketScholar so I could have changed that earlier!\n\n" +
      "Completing my homework in a timely manner and spending hours at sports practices and games, I felt as if I was busy every day of the week. In reality I was cheating myself. Despite my perceived busyness, I still had ample free time which I chose to exhaust with activities that provided little else but entertainment. While the time you enjoy wasting isn’t truly wasted, you will discover that there are much better alternatives that can give you the best of both worlds.\n\n" +
      "For me, grades nine and ten seemed to pass far too quickly. At the end of the two short years, I came to the realization that by sticking to the familiar, I had missed out on an amazing window of opportunity to explore what else life has to offer. While I still had many stimulants for growth during those early highschool years, I now frequently look back and remind myself that with the limited time you have, simply being comfortable is a luxury. You should strive for nothing less than excellence.\n\n" +
      "Through my personal experiences, I hope to ensure that once having interacted with PocketScholar, you will take the opportunity to use your time more effectively, further engage with your community, begin to learn valuable new skills, take more initiative, and seek to be a leader.\n\n",
    whyDoesPsExist2:
      "Post-secondary education can be an incredible time of growth and self-discovery, but for many students, it comes at a significant cost. According to Statistics Canada, between 2000 and 2015, one in two post-secondary graduates had student debt at graduation, with this trend holding firm in recent years.\n\n" +
      "The ‘Student Debt Crisis’ is a familiar phrase for the majority of Canadians, but many don’t recognize the weight that it carries. Fewer still, are the students like you and I that understand how student debt could influence the way we live our lives in the future.\n\n" +
      "There is an alarming amount of students who graduate <i>tens of thousands of dollars</i> in student debt, which can take years to repay. Moreover, it is reported that in Canada during 2018, student debt contributed to about 18% of insolvencies (people not being able to pay their debts on time). The average student debtor was 35 years old and still had almost $15,000 in student debt, making up over 30% of their debt to repay!\n\n" +
      "By holding debt for an extended period of time as a young adult, you rob yourself of one of your greatest wealth-building tools: <i>compound interest.</i> To learn more about the powers of compound interest, visit the Resources page of PocketScholar.\n\n" +
      "When you’re debt-free and you wield your own financial freedom, the world will present you with endless opportunities. An oppressive weight lifted off your shoulders, being in control of your financial health opens you up to many possibilities for generosity, risk-taking, creativity, and ultimately, fulfillment.\n\n" +
      "Winning scholarships is clearly not the only way to help finance your education, but it is definitely the most time effective way to do so. Additionally, instilling yourself with the values of a scholarship winner will carry through into your personal relationships, career, and beyond. After stirring up the ideas to give yourself a running start, you’ll be on track to leading the life you want to live, while uplifting others along the way.\n\n",
    psInfoPages:
      "PocketScholar’s three information pages offer the bulk of lessons that my research and  experiences have to offer. Each page provides relevant discourse on how to become the best you that you can be!\n\n" +
      "While they are solely text, the information pages are for anything but passive reading. Instead, you’re encouraged to engage with the written content. Start by asking (but don’t limit yourself to) the following questions about what you read during and after every section:\n\n" +
      "- Do I understand what’s being said? If so, do I agree with it? Why or why not?\n\n" +
      "- Am I practicing what I agree with? If not, what’s stopping me? (Answer: probably nothing!)\n\n" +
      "- What can I do to better apply the principles that I’ve discovered?\n\n" +
      "By participating in this manner, you’re much more likely to spark something within yourself that will drive you forward while working towards your aspirations. If you feel like you don't have particular aspirations yet, don’t worry, you’ll have a better time finding them with PocketScholar at your side!\n\n" +
      "Additional thought provoking questions will turn up throughout each section. Take your time to answer them first by yourself, then with others as well. Answering the questions above is a great first step, but they mean nothing if your behaviour doesn’t change. Get out there and use your newfound knowledge to make yourself extraordinary!\n\n",
    aboutPage:
      "The About page is your one-stop shop on learning how to use PocketScholar to its maximum potential. It contains the background information on why you should take control of your future now, and it also gives you the tools for learning how to do so!\n\n",
    getStartedPage:
      "It will take lots of time and energy, but the quest for improvement is definitely worth it. The Get Started page ensures that your time and energy is well spent and that you’re rewarded for your efforts.\n\n" +
      "However, your rewards will not only come in the form of scholarships. When you grow as a result of your work, you’ll find that you gain confidence, meaningful relationships, and useful skills. You will have likely helped others along the way, and demonstrated excellence or innovation in fields of your interest. You’ll know you have grown as a person, and you won't need to win any scholarships to validate that fact!\n\n" +
      "The Get Started page will outline steps to take as you navigate your environment. There are no one-size-fits-all guidelines that can be provided to guarantee your progress, but with the help of versatile advice, learning from others’ experiences, and some active self-reflection, you are entirely capable of producing a personalized plan of action that will work for you.\n\n",
    challengesPage:
      "There are plenty of challenges that you may run into when you are striving to be your best, so contrary to how it may appear, the Challenges page isn’t there to give you more. In fact, it will highlight some of the toughest hurdles you might encounter and offer methods which you can take advantage of to overcome them!\n\n",
    psInteractable:
      "It wouldn’t be an app without some more things to press! PocketScholar’s interactable pages offer space to lay out all your thoughts and experiences in one convenient place.\n\n" +
      "Take the time to review what you have accomplished and where to head next. Stepping back to take a look at the big picture is an indispensable habit that you should form as soon as possible, the more you do it, the more you notice how much doing so helps!\n\n" +
      "Coming back to PocketScholar will remind you of how far you’ve progressed and energize you for what’s to come. As you get more involved, scout out scholarships, or learn something new about yourself, you have a place to instantly record it. Just reach for your pocket!\n\n",
    activityList:
      "The Activity List will help you keep track and quantify all of the activities that you partake in, whether they are for leisure, hobbies, clubs, sports, councils, competitions, volunteer initiatives, internships, jobs, you name it!\n\n" +
      "<b>Fields:</b>\n" +
      "<i>Name:</i> The name of the activity you participated in or the organization it belonged to (eg: Greenpeace Canada)\n\n" +
      "<i>Period of Involvement:</i> The date at which you began the activity and the date you ended * or whether the activity is ongoing* (eg: April 2019 - February 2021)\n\n" +
      "<i>Commitment:</i> The amount of time you commit to the activity, measured in either hours/week or hours/month (eg: 2h/week)\n\n" +
      "<i>Key Roles/Responsibilities:</i> What are you responsible for in the activity and how does that impact others? (eg: Event Coordinator: organized a food drive for homeless shelters in order to reduce the environmental impact of food waste)\n\n" +
      "<i>Awards / Achievements:</i> What have you accomplished in your role? Have you won any awards? Think of what that says about your character. (eg: Initiated over 400 contributions to food drives, eliminating over 60kg of food wastage)\n\n" +
      "By keeping a record of your involvement with your community, there is quite a bit of information that you can extrapolate from the data. Here are some examples of questions to ask yourself:\n\n" +
      "<b>Specific to each activity:<b/>\n" +
      "-> What was the end goal of this activity? Were there any lasting results?\n-> What skills or lessons did I learn while participating in this activity?\n-> What roles/responsibilities did I take on which challenged me? How did I grow from them?\n-> What do my accomplishments and awards say about my character?\n\n" +
      "<b>Big Picture Questions:<b/>\n" +
      "-> Do I often pursue leadership roles? If not, why?\n-> Am I committed to any activities or do I bounce from one to another without real investment?\n-> Am I doing things that I am passionate about?\n-> How much of my time is spent productively? (Learning, improving, providing value, helping others)\n\n" +
      "From just a few simple questions, you can reveal a very large amount about who you are and your motivations. If you are unsatisfied with your answers, don’t run, hide, or worry! Once you make the simple decision to improve yourself and once you get the ball rolling, you’ll find how fulfilling it is to be pleased with your answers!\n\n",
    tracker:
      "Since inspiring you to win scholarships is the principal objective of PocketScholar, a scholarship tracker is pretty much a requirement! Using PocketScholar’s Resources page alongside your own research, it should be relatively easy to load the tracker full of scholarships relevant to your interests and circumstances. *None of the following examples are in any way related*\n\n" +
      "<b>Fields:</b>\n" +
      "<i>Name:</i> The name of the scholarship / the organization that provides it (eg: TD Community Leadership)\n\n" +
      "<i>Deadline:</i> The date that submissions are due (eg: March 16th, 2023)\n\n" +
      "<i>Value:</i> The amount of money the scholarship is worth (eg: $10,000,000!)\n\n" +
      "<i>Criteria / Special Requirements:</i> Some scholarships have specific criteria to be eligible to win (eg: specific to engineering students) (eg: must be / be the child of someone employed at [company])\n\n" +
      "<i>Essay Topic:</i> Does this scholarship require an essay or written component? What is it about? (eg: How should countries approach the needs of public health vs. those of individual privacy?)\n\n",
    promptsPage:
      "The Prompts page is likely the most demanding component of PocketScholar, and it has good reason to be. These prompts mimic similar ones on real scholarship applications, asking you to expand upon the conclusions drawn from your activity list and to back up your thoughts with evidence of your growth.\n\n" +
      "It sounds like a tough job, but after completing the Prompts page, you will have already done much of the work required to apply for even the most prestigious of scholarships!\n\n" +
      "It may help to store your fully fleshed out answers elsewhere, but as ideas pop up throughout your day, jot them down immediately under the prompt they relate to so that you can reference them later.\n\n" +
      "Don’t walk away from PocketScholar without being able to thoroughly answer all of the prompts while being genuinely proud of your answers! How much have you grown since picking up PocketScholar? What have you accomplished? What great things are foreshadowed by your successes thus far?\n\n",
    resourcesPage:
      "The Resources page acts as a bridge to link the ideas presented in PocketScholar to other amazing sources of knowledge that reach beyond the scope of the content covered within the app.\n\n" +
      "<b>There you will find:</b>\n\n" +
      "<i>Scholarship Search Engines</i> - you can take a look at scholarships which are up for grabs and learn more about post-secondary education.\n\n" +
      "<i>Book Recommendations</i> -  a collection of some of my favorite reads that have relevant connections to the goals of PocketScholar.\n\n" +
      "<i>Additional Resources</i> - to help you go above and beyond what PocketScholar has to offer and continue your self learning.\n\n" +
      "<i>Sources</i> - my english teacher would be mad at me otherwise.\n\n" +
      "PocketScholar is just the beginning, and there’s so much more to learn! Of course if you still have questions there are certainly other places which will hold the answers you’re looking for. Although if you are ever feeling uncertain or don’t know where to look next, return to PocketScholar and collect your thoughts.\n\n" +
      "I have the utmost faith in you. You can do it!\n\n",
    notes:
      "<b>1)</b> If you’re a student yourself, congratulations! Taking initiative and putting yourself in the position to become a scholar early is an undertaking that too many forgo. Fortunately, you’re not alone. Introduce PocketScholar to your parents, teachers, siblings, friends, and others that could either discuss the content with you and help you along your journey, or benefit from PocketScholar themselves!\n\n" +
      "<b>2)</b> In the case that you’re a parent, relative, teacher, coach, or friend, if you know someone who’s future you could impact by giving them access to PocketScholar, don’t do them a disservice! You have the possibility to positively influence someone’s future by accelerating their journey towards success. There’s no reason not to!\n\n" +
      "<b>3)</b> PocketScholar should keep you coming back. As you grow your Activities List, answer all the Prompts, and fill out the Scholarship Tracker, you should frequently reference the About, Get Started, and Challenges pages. Use the time to reflect on your progress, ensure you’re on the right track, and admire how far you’ve come!\n\n" +
      "<b>4)</b> PocketScholar is not a guide for applying to scholarships, but a guide on how to be an amazing candidate for them. Once you go above and beyond, applications will be a breeze! When it is time to finally start searching (grade 11 recommended) and applying (usually grade 12), you can find many scholarship search engines on the Resources page.\n\n" +
      "<b>5)</b> Some of PocketScholar’s resources are targeted for Canadians. But if you’re not a Canuck, don’t let that dissuade you from the rest of the content! The principles you’ll learn can be applied anywhere on the globe.\n\n",
  },
  challengesText: {},
};
// "\n\n" +
